
platformName: Android
platformVersion: 5.1
udid: Y15QKBP6234TM
deviceName: MEIZU
appPackage: com.hs.mywork.activity
appActivity: com.hs.mywork.activity.WelcomeActivity
noReset: True
unicodeKeyboard: True
resetKeyboard: True
automationName: uiautomator2
ip: 127.0.0.1
port: 4723

